capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import logout

app_name = 'CreateSurvey'

urlpatterns = [

    # creation homepage
    path('', views.IndexView.as_view(), name='index'),

    # registration
    path('registration/', views.UserFormView.as_view(), name='registration'),

    # login
    path('login/', views.login_view, name='login'),

    # logout
    path('logout/', views.logout_view, name='logout'),

    # specific survey
    path('survey/<pk>/', views.DetailsView.as_view(), name='details'),

    # create survey
    path('survey-add/', views.SurveyCreate.as_view(), name='survey-add'),

    # create question
    path('survey/<pk>/question-add/', views.QuestionCreate.as_view(), name='question-add'),

    # update survey
    path('survey/<pk>/update-survey/', views.SurveyUpdate.as_view(), name='survey-update'),

    # update question
    path('survey/<survey>/update-question/<pk>', views.QuestionUpdate.as_view(), name='question-update'),

    # delete survey
    path('survey/<pk>/delete-survey/', views.SurveyDelete.as_view(), name='survey-delete'),

    # delete question
    path('survey/<survey>/delete-question/<pk>', views.QuestionDelete.as_view(), name='question-delete'),

    # add response
    path('survey/<pk>/response-add/', views.ResponseCreate.as_view(), name='response-add'),

    # submit response
    path('survey/response-submit/<pk>', views.submit, name='response-submit'),

    # delete response
    path('survey/<survey>/survey-results/', views.SurveyResults.as_view(), name='survey-results'),
    path('survey/<survey>/response-delete/<pk>', views.ResponseDelete.as_view(), name='response-delete'),

    # specific take-survey
    path('survey/<survey>/take-survey/<pk>', views.TakeSurvey.as_view(), name='take-survey'),

    # add answer
    path('take-survey/<pk>/answer-add/', views.AnswerCreate.as_view(), name='answer-add'),
    path('take-survey/<pk>/answer-add/<question>', views.AnswerCreate.as_view(), name='answer-add'),

    # update answer
    path('take-survey/<response>/update-answer/<pk>', views.AnswerUpdate.as_view(), name='answer-update'),

    # delete answer
    path('take-survey/<response>/delete-answer/<pk>', views.AnswerDelete.as_view(), name='answer-delete'),

    # view results
    path('survey/<pk>/view-results', views.ResultsView.as_view(), name='view-results'),

    # survey result
    path('survey/<survey>/survey-results/', views.SurveyResults.as_view(), name='survey-results'),
    path('survey/<survey>/survey-results/<pk>', views.SurveyResults.as_view(), name='survey-results')

]

urlpatterns += staticfiles_urlpatterns()

capstone-spring-2018-team-6/EncryptedSurveyTool/EncryptedSurveyTool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('CreateSurvey/', include('CreateSurvey.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', views.login, name='login'),
    path('accounts/logout/', views.logout, name='logout', kwargs={ 'next_page': '/'}),
]

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/models.py
from django.db import models
from django.urls import reverse
import uuid
from pgcrypto_expressions.fields import EncryptedTextField


class Survey(models.Model):
    survey_title = models.CharField(max_length=500)
    # anonymous = models.BooleanField(default=False)

    def __str__(self):
        return str(self.survey_title)

    def get_absolute_url(self):
        return reverse('CreateSurvey:details', kwargs={'pk': self.pk})


class Question(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    question_field = models.CharField(max_length=500)
    # encrypted = models.BooleanField(default=False)

    def __str__(self):
        return str(self.question_field)

    def get_absolute_url(self):
        return reverse('CreateSurvey:details', kwargs={'pk': self.survey_id})


class Response(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    interview_uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    submitted = models.BooleanField(default=False)

    def __unicode__(self):
        return "response %s" % self.interview_uuid

    def get_absolute_url(self):
        return reverse('CreateSurvey:take-survey', kwargs={'pk': self.pk, 'survey': self.survey_id})


class Answer(models.Model):
    response = models.ForeignKey(Response, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_field = EncryptedTextField(max_length=500)

    class Meta:
        unique_together = ('response', 'question')

    def __str__(self):
        return str(self.answer_field)

    def get_absolute_url(self):
        return reverse('CreateSurvey:take-survey', kwargs={'pk': self.response_id, 'survey': self.response.survey_id})

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from .models import Survey, Question, Response, Answer
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.http import HttpResponse
from .forms import UserForm


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = "CreateSurvey/index.html"
    context_object_name = 'all_surveys'

    def get_queryset(self):
        return Survey.objects.all()


class DetailsView(LoginRequiredMixin, generic.DetailView):
    model = Survey
    template_name = 'CreateSurvey/details.html'


class TakeSurvey(generic.DetailView):
    model = Response
    template_name = 'CreateSurvey/take-survey.html'


class ResponseCreate(CreateView):
    model = Response
    fields = []

    def form_valid(self, form):
        form.instance.survey_id = self.kwargs.get('pk')
        return super(ResponseCreate, self).form_valid(form)


def submit(request, pk):
    response = Response.objects.get(pk=pk)
    response.submitted = True
    response.save()
    return redirect(response)


class ResponseDelete(LoginRequiredMixin, DeleteView):
    model = Response

    def get_success_url(self, **kwargs):
        survey = self.object.survey
        return reverse_lazy("CreateSurvey:view-results", kwargs={'pk': survey.id})


class SurveyCreate(LoginRequiredMixin, CreateView):
    model = Survey
    fields = ['survey_title']


class SurveyUpdate(LoginRequiredMixin, UpdateView):
    model = Survey
    fields = ['survey_title']


class SurveyDelete(LoginRequiredMixin, DeleteView):
    model = Survey
    success_url = reverse_lazy('CreateSurvey:index')


class QuestionCreate(LoginRequiredMixin, CreateView):
    model = Question
    fields = ['question_field']

    def form_valid(self, form):
        form.instance.survey_id = self.kwargs.get('pk')
        return super(QuestionCreate, self).form_valid(form)


class QuestionUpdate(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['question_field']


class QuestionDelete(LoginRequiredMixin, DeleteView):
    model = Question

    def get_success_url(self, **kwargs):
        survey = self.object.survey
        return reverse_lazy("CreateSurvey:details", kwargs={'pk': survey.id})


class AnswerCreate(CreateView):
    model = Answer
    fields = ['answer_field']

    def form_valid(self, form):
        form.instance.response_id = self.kwargs.get('pk')
        form.instance.question_id = self.kwargs.get('question')
        return super(AnswerCreate, self).form_valid(form)


class AnswerUpdate(UpdateView):
    model = Answer
    fields = ['answer_field']


class AnswerDelete(DeleteView):
    model = Answer

    def get_success_url(self, **kwargs):
        response = self.object.response
        return reverse_lazy("CreateSurvey:take-survey", kwargs={'pk': response.id})


class ResultsView(generic.DetailView):
    model = Survey
    template_name = 'CreateSurvey/view-results.html'


class SurveyResults(generic.DetailView):
    model = Response
    template_name = 'CreateSurvey/survey-results.html'


def logout_view(request):
    logout(request)
    return redirect('CreateSurvey:index')


def login_view(request):
    logout(request)
    return redirect('CreateSurvey:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'CreateSurvey/registration.html'

    # blank form display
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('CreateSurvey:index')

        return render(request, self.template_name, {'form': form})

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/answer_form.html
{% extends 'CreateSurvey/template.html' %}
{% block title %}Create a New Response{% endblock %}
{% block surveys_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Enter your response:</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'CreateSurvey/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/details.html
{% extends 'CreateSurvey/template.html' %}
{% block title %}{{ survey }}{% endblock %}
{% block body %}

<div class="container-fluid questions-container">
    <div class="row">

        <!-- Left Survey Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1>{{ survey.survey_title }}</h1>
{#                    <h2>Anonymous: {{ survey.anonymous }}</h2>#}
                </div>
            </div>
        </div>

        <!-- Right Survey Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
{#                <li role="presentation" class="active">#}
{#                    <a href="{% url 'CreateSurvey:details' survey.id %}">View All</a></li>#}
                <li role="presentation" class="active">
                    <a href="{% url 'CreateSurvey:question-add' survey.id %}">Add Question</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>All Questions</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Number</th>
                            <th>Question</th>
{#                            <th>Encrypted</th>#}
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for question in survey.question_set.all  %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ question.question_field }}</td>
{#                                <td>{{ question.encrypted }}</td>#}
                                <td>
                                    <a href="{% url 'CreateSurvey:question-update' survey.id question.id  %}" class="btn-favorite">
                                    <button type="submit" class="btn btn-success btn-xs">
                                        <span class="glyphicon glyphicon-edit"></span>&nbsp; Update
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <form action="{% url 'CreateSurvey:question-delete' survey.id question.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="question_id" value="{{ question.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                             </tr>
                    {% endfor %}
                    </tbody>
             </table>
             </div>
        </div>
     </div>
    </div>
</div>

{% endblock %}

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/index.html
{% extends 'CreateSurvey/template.html' %}

{% block body %}
{% if all_surveys %}
<ul>
    <h3>Surveys so far:</h3>
    {% for survey in all_surveys %}
                <div class="col-sm-4 col-md-2">
                    <div class="thumbnail">
                        <a href="{% url 'CreateSurvey:details' survey.id %}">
                            <img src="static/CreateSurvey/images/boozallen.png" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ survey.survey_title }}</h2>
{#                            <h4>Anonymous: {{ survey.anonymous }}</h4>#}

                            <!-- View Details -->
                            <a href="{% url 'CreateSurvey:details' survey.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Update Survey -->
                            <form action="{% url 'CreateSurvey:survey-update' survey.id %}" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="survey_id" value="{{ survey.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>
                            </form>

                            <!-- View Results -->
                            <form action="{% url 'CreateSurvey:view-results' survey.id %}" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="survey_id" value="{{ survey.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-check"></span>
                                </button>
                            </form>

                            <!-- Share -->
                            <form action="{% url 'CreateSurvey:response-add' survey.id %}" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="survey_id" value="{{ survey.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-share"></span>
                                </button>
                            </form>

                            <!-- Delete Survey -->
                            <form action="{% url 'CreateSurvey:survey-delete' survey.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="survey_id" value="{{ survey.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
    {% endfor %}
</ul>
{% else %}
<h3>No surveys yet</h3>
{% endif %}
{% endblock %}

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/question_form.html
{% extends 'CreateSurvey/template.html' %}
{% block title %}Create a New Question{% endblock %}
{% block surveys_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Question</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'CreateSurvey/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/registration.html
{% extends 'CreateSurvey/template.html' %}
{% block title %}Registration{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'CreateSurvey/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/survey-results.html
{% extends 'CreateSurvey/template.html' %}
{% block title %}{{ survey }}{% endblock %}
{% block body %}

<div class="container-fluid questions-container">
    <div class="row">
        <!-- Right Survey Info -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>{{ survey.survey_title }}</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
<div style="display: inline-table">
                    <table class="table">
                        <tr>
                            <th>Number</th>
                            <th>Question</th>
                        </tr>
                        <tbody>
                        {% for question in response.survey.question_set.all %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ question.question_field }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
</div>
                <div style="display: inline-table">
                <table class="table">
                    <tr>
                        <th>Response</th>
                    </tr>
                <tbody>
                        {% for answer in response.answer_set.all  %}
                            <tr>
                                <td>{{ answer.answer_field }}</td>
                            </tr>
                        {% endfor %}
                </tbody>
                </table>
                </div>

             </div>
        </div>
     </div>
    </div>
</div>

{% endblock %}

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/take-survey.html
{% extends 'CreateSurvey/template.html' %}
{% block title %}{{ survey }}{% endblock %}
{% block body %}

    {% if response.submitted == False %}
<div class="container-fluid questions-container">
    <div class="row">
        <!-- Right Survey Info -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>{{ response.survey.survey_title }}</h3>
                    {% if error_message %}
                        <p><strong>{{ "SURVEY NOT FOUND" }}</strong></p>
                    {% endif %}
<div style="display: inline-table">
                    <table class="table">
                        <tr>
                            <th>Number</th>
                            <th>Question</th>
                        </tr>
                        <tbody>
                        {% for question in response.survey.question_set.all  %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ question.question_field }}</td>
                                {% if response.answer_set.count == forloop.counter0  %}
                                <td>
                                    <a href="{% url 'CreateSurvey:answer-add' response.id question.id %}" class="btn-favorite">
                                    <button type="submit" class="btn btn-success btn-xs">
                                        <span class="glyphicon glyphicon-create"></span>&nbsp; Create Response
                                        </button>
                                    </a>
                                </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
             </table>
</div>
                <div style="display: inline-table">
                <table class="table">
                    <tr>
                        <th>Response</th>
                    </tr>
                <tbody>
                        {% for answer in response.answer_set.all %}
                            <tr>
                                <td>{{ answer.answer_field }}</td>
                                <td>
                                    <a href="{% url 'CreateSurvey:answer-update' response answer.id %}" class="btn-favorite">
                                    <button type="submit" class="btn btn-success btn-xs">
                                        <span class="glyphicon glyphicon-edit"></span>&nbsp; Update Response
                                        </button>
                                    </a>
                                </td>
                            </tr>
                    {% endfor %}
                </tbody>
                </table>

                </div>
                                <a href="{% url 'CreateSurvey:response-submit' response.id %}">
                                    {% csrf_token %}
                                <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-success">
                                    Submit
                                </button>
                            </div>
                                    </a>
             </div>
        </div>
     </div>
    </div>
</div>
        {% else %}
        <p><strong>{{ "SURVEY SUBMITTED" }}</strong></p>
    {% endif %}

{% endblock %}

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Encrypted Survey Tool{% endblock %}</title>

    <!-- Loads path to static files -->

{% load staticfiles %}
<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'CreateSurvey/style.css' %}"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</head>


    <!-- Navbar -->

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand" href="{% url 'CreateSurvey:index' %}">Booz | Allen | Hamilton</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNav">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'CreateSurvey:survey-add' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;
                        Create Surveys
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'CreateSurvey:index' %}">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp;
                        Manage Surveys
                    </a>
                </li>
            </ul>
{#            <form class="navbar-form navbar-left" role="search" method="get" action="{%  url 'CreateSurvey:index' %}">#}
{#                <div class="form-group">#}
{#                    <input type="text" class="form-control" name="query" value="{{ request.GET.query }}">#}
{#                </div>#}
{#                <button type="submit" class="btn btn-inverse">Search</button>#}
{#            </form>#}
            <ul class="nav navbar-nav navbar-right">
                   {% if user.is_authenticated %}
                   <li class="active">
                    <a href= {% url "CreateSurvey:logout" %}>
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                    {% else %}
                    <li class="active">
                    <a href= {% url "CreateSurvey:login" %}>
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Login
                    </a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</html>

capstone-spring-2018-team-6/EncryptedSurveyTool/CreateSurvey/templates/CreateSurvey/view-results.html
{% extends 'CreateSurvey/template.html' %}

{% block body %}
{% if survey.response_set %}
<ul>
    <h3>Responses so far</h3>
    {% for response in survey.response_set.all %}
                <div class="col-sm-4 col-md-2">
                    <div class="thumbnail">
                        <div class="caption">
                            <h2>{{ survey.survey_title }}</h2>
                            <h4>ID: {{ response.interview_uuid }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'CreateSurvey:survey-results' survey.id response.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Survey -->
                            <form action="{% url 'CreateSurvey:response-delete' survey.id response.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="survey_id" value="{{ survey.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
    {% endfor %}
</ul>
{% else %}
<h3>No responses yet</h3>
{% endif %}
{% endblock %}